# Stage 1: Build the React app
FROM node:18-alpine as build

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files
# to the working directory and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the React app files to the working directory
COPY . .

# Build the production version of the React app
RUN npm run build

# Stage 2: Create a lightweight production image
FROM nginx:alpine

# Copy the built React app from the previous stage to the Nginx web server directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 to allow incoming connections
EXPOSE 80

# Start the Nginx web server
CMD ["nginx", "-g", "daemon off;"]
