/**
 * Excel Generator
 * 
 * Generates professional Excel reports with NEM Insurance branding,
 * including multi-sheet structure, formatted headers, charts, and
 * proper data formatting.
 * 
 * Requirements: 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11
 */

import ExcelJS from 'exceljs';
import type { NEMBranding } from './BrandingService';
import type {
  AnalyticsSummary,
  UsageDataPoint,
  BrokerUsage,
  AuditLogEntry,
} from '../../types/analytics';

export interface ReportData {
  summary?: AnalyticsSummary;
  usageData?: UsageDataPoint[];
  brokerUsage?: BrokerUsage[];
  auditLogs?: AuditLogEntry[];
}

export interface ReportMetadata {
  title: string;
  generatedAt: Date;
  generatedBy: string;
  dateRange: {
    start: Date;
    end: Date;
  };
  filters?: {
    provider?: string;
    status?: string;
  };
}

interface ExcelGeneratorOptions {
  branding: NEMBranding;
  includeCharts: boolean;
}

export class ExcelGenerator {
  /**
   * Generates complete Excel workbook with formatting
   * 
   * Requirements: 3.1, 3.2, 3.3
   */
  async generate(
    data: ReportData,
    metadata: ReportMetadata,
    sections: string[],
    options: ExcelGeneratorOptions
  ): Promise<Blob> {
    console.log('Excel Generator - Data received:', {
      hasSummary: !!data.summary,
      usageDataCount: data.usageData?.length || 0,
      brokerUsageCount: data.brokerUsage?.length || 0,
      auditLogsCount: data.auditLogs?.length || 0,
      sections
    });

    const workbook = new ExcelJS.Workbook();
    
    // Set workbook properties
    workbook.creator = metadata.generatedBy;
    workbook.created = metadata.generatedAt;
    workbook.title = options.branding.title;

    // Create Summary sheet first
    this.createSummarySheet(workbook, data, metadata, options.branding);

    // Create section sheets
    if (sections.includes('overview') && data.summary) {
      this.createOverviewSheet(workbook, data.summary, options.branding);
    }

    if (sections.includes('usage-charts') && data.usageData && data.usageData.length > 0) {
      this.createUsageDataSheet(workbook, data.usageData, options.branding);
    }

    if (sections.includes('broker-attribution') && data.brokerUsage && data.brokerUsage.length > 0) {
      this.createBrokerUsageSheet(workbook, data.brokerUsage, options.branding);
    }

    if (sections.includes('audit-logs') && data.auditLogs && data.auditLogs.length > 0) {
      this.createAuditLogsSheet(workbook, data.auditLogs, options.branding);
    }

    // Generate binary data
    const buffer = await workbook.xlsx.writeBuffer();
    console.log('Excel buffer size:', buffer.byteLength);
    return new Blob([buffer], {
      type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    });
  }

  /**
   * Creates summary sheet with key metrics
   * 
   * Requirements: 3.1, 3.2
   */
  private createSummarySheet(
    workbook: ExcelJS.Workbook,
    data: ReportData,
    metadata: ReportMetadata,
    branding: NEMBranding
  ): void {
    const sheet = workbook.addWorksheet('Summary', { views: [{ state: 'frozen', ySplit: 1 }] });

    // Add title row with NEM branding
    const titleRow = sheet.addRow([branding.title]);
    titleRow.font = { size: 16, bold: true, color: { argb: 'FFFFFFFF' } };
    titleRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF800020' }, // Burgundy
    };
    titleRow.height = 30;
    titleRow.alignment = { vertical: 'middle', horizontal: 'left' };
    sheet.mergeCells('A1:B1');

    // Add empty row
    sheet.addRow([]);

    // Add metadata
    sheet.addRow(['Generated:', metadata.generatedAt.toLocaleString()]);
    sheet.addRow(['Generated By:', metadata.generatedBy]);
    sheet.addRow([
      'Period:',
      `${metadata.dateRange.start.toLocaleDateString()} - ${metadata.dateRange.end.toLocaleDateString()}`,
    ]);

    if (metadata.filters?.provider && metadata.filters.provider !== 'all') {
      sheet.addRow(['Provider Filter:', metadata.filters.provider]);
    }
    if (metadata.filters?.status && metadata.filters.status !== 'all') {
      sheet.addRow(['Status Filter:', metadata.filters.status]);
    }

    // Add empty row
    sheet.addRow([]);

    // Add key metrics if available
    if (data.summary) {
      const metricsHeaderRow = sheet.addRow(['Key Metrics', '']);
      this.formatSheetHeader(metricsHeaderRow, branding);
      
      sheet.addRow(['Total Calls', data.summary.totalCalls]);
      sheet.addRow(['Total Cost', data.summary.totalCost]);
      sheet.addRow(['Success Rate', data.summary.successRate / 100]); // Convert to decimal for percentage format
      sheet.addRow(['Datapro Calls', data.summary.dataproCalls]);
      sheet.addRow(['VerifyData Calls', data.summary.verifydataCalls]);
    }

    // Format columns
    sheet.getColumn(1).width = 25;
    sheet.getColumn(2).width = 40;

    // Apply formatting to data rows
    this.applyBrandedFormatting(sheet, branding);
  }

  /**
   * Creates overview sheet
   */
  private createOverviewSheet(
    workbook: ExcelJS.Workbook,
    summary: AnalyticsSummary,
    branding: NEMBranding
  ): void {
    const sheet = workbook.addWorksheet('Overview', { views: [{ state: 'frozen', ySplit: 1 }] });

    // Add header row
    const headerRow = sheet.addRow(['Metric', 'Value']);
    this.formatSheetHeader(headerRow, branding);

    // Add data rows
    sheet.addRow(['Total Calls', summary.totalCalls]);
    sheet.addRow(['Total Cost', summary.totalCost]);
    sheet.addRow(['Success Rate', summary.successRate / 100]);
    sheet.addRow(['Failure Rate', summary.failureRate / 100]);
    sheet.addRow(['Datapro Calls', summary.dataproCalls]);
    sheet.addRow(['Datapro Cost', summary.dataproCost]);
    sheet.addRow(['VerifyData Calls', summary.verifydataCalls]);
    sheet.addRow(['VerifyData Cost', summary.verifydataCost]);

    // Format columns
    sheet.getColumn(1).width = 25;
    sheet.getColumn(2).width = 20;

    // Apply number formats
    sheet.getColumn(2).eachCell((cell, rowNumber) => {
      if (rowNumber > 1) {
        const metric = sheet.getCell(rowNumber, 1).value as string;
        if (metric.includes('Cost')) {
          cell.numFmt = '₦#,##0.00'; // Nigerian Naira with 2 decimals
        } else if (metric.includes('Rate')) {
          cell.numFmt = '0.0%'; // Percentage with 1 decimal
        }
      }
    });

    this.applyBrandedFormatting(sheet, branding);
  }

  /**
   * Creates usage data sheet
   */
  private createUsageDataSheet(
    workbook: ExcelJS.Workbook,
    usageData: UsageDataPoint[],
    branding: NEMBranding
  ): void {
    const sheet = workbook.addWorksheet('Usage Data', { views: [{ state: 'frozen', ySplit: 1 }] });

    // Add header row
    const headerRow = sheet.addRow([
      'Date',
      'Datapro Calls',
      'VerifyData Calls',
      'Total Calls',
      'Datapro Cost',
      'VerifyData Cost',
      'Total Cost',
      'Success Count',
      'Failure Count',
    ]);
    this.formatSheetHeader(headerRow, branding);

    // Add data rows
    usageData.forEach((d) => {
      sheet.addRow([
        d.date,
        d.dataproCalls,
        d.verifydataCalls,
        d.totalCalls,
        d.dataproCost,
        d.verifydataCost,
        d.totalCost,
        d.successCount,
        d.failureCount,
      ]);
    });

    // Format columns
    sheet.getColumn(1).width = 12; // Date
    sheet.getColumn(2).width = 15;
    sheet.getColumn(3).width = 15;
    sheet.getColumn(4).width = 12;
    sheet.getColumn(5).width = 12;
    sheet.getColumn(6).width = 15;
    sheet.getColumn(7).width = 12;
    sheet.getColumn(8).width = 15;
    sheet.getColumn(9).width = 15;

    // Apply number formats
    [5, 6, 7].forEach((col) => {
      sheet.getColumn(col).numFmt = '₦#,##0.00';
    });

    this.applyBrandedFormatting(sheet, branding);
  }

  /**
   * Creates broker usage sheet
   */
  private createBrokerUsageSheet(
    workbook: ExcelJS.Workbook,
    brokerUsage: BrokerUsage[],
    branding: NEMBranding
  ): void {
    const sheet = workbook.addWorksheet('Broker Usage', { views: [{ state: 'frozen', ySplit: 1 }] });

    // Add header row
    const headerRow = sheet.addRow([
      'Broker Name',
      'Broker Email',
      'Total Calls',
      'Datapro Calls',
      'VerifyData Calls',
      'Total Cost',
      'Success Rate',
      'Last Activity',
    ]);
    this.formatSheetHeader(headerRow, branding);

    // Add data rows
    brokerUsage.forEach((b) => {
      // Handle different date formats
      let lastActivity: any = b.lastActivity;
      if (lastActivity && typeof lastActivity === 'object' && 'toDate' in lastActivity) {
        lastActivity = lastActivity.toDate();
      } else if (typeof lastActivity === 'string') {
        lastActivity = new Date(lastActivity);
      }
      
      sheet.addRow([
        b.userName,
        b.userEmail,
        b.totalCalls,
        b.dataproCalls,
        b.verifydataCalls,
        b.totalCost,
        b.successRate / 100,
        lastActivity,
      ]);
    });

    // Format columns
    sheet.getColumn(1).width = 25;
    sheet.getColumn(2).width = 30;
    sheet.getColumn(3).width = 12;
    sheet.getColumn(4).width = 15;
    sheet.getColumn(5).width = 15;
    sheet.getColumn(6).width = 12;
    sheet.getColumn(7).width = 12;
    sheet.getColumn(8).width = 20;

    // Apply number formats
    sheet.getColumn(6).numFmt = '₦#,##0.00';
    sheet.getColumn(7).numFmt = '0.0%';
    sheet.getColumn(8).numFmt = 'yyyy-mm-dd hh:mm:ss';

    this.applyBrandedFormatting(sheet, branding);
  }

  /**
   * Creates audit logs sheet
   */
  private createAuditLogsSheet(
    workbook: ExcelJS.Workbook,
    auditLogs: AuditLogEntry[],
    branding: NEMBranding
  ): void {
    const sheet = workbook.addWorksheet('Audit Logs', { views: [{ state: 'frozen', ySplit: 1 }] });

    // Add header row
    const headerRow = sheet.addRow([
      'Timestamp',
      'User',
      'Provider',
      'Type',
      'Status',
      'Cost',
      'IP Address',
      'Error Message',
    ]);
    this.formatSheetHeader(headerRow, branding);

    // Add data rows
    auditLogs.forEach((log) => {
      // Handle different timestamp formats
      let timestamp: any = log.timestamp;
      if (timestamp && typeof timestamp === 'object' && 'toDate' in timestamp) {
        timestamp = timestamp.toDate();
      } else if (typeof timestamp === 'string') {
        timestamp = new Date(timestamp);
      }
      
      sheet.addRow([
        timestamp,
        log.userName,
        log.provider,
        log.verificationType,
        log.status,
        log.cost,
        log.ipAddress,
        log.errorMessage || '',
      ]);
    });

    // Format columns
    sheet.getColumn(1).width = 20;
    sheet.getColumn(2).width = 25;
    sheet.getColumn(3).width = 12;
    sheet.getColumn(4).width = 10;
    sheet.getColumn(5).width = 10;
    sheet.getColumn(6).width = 10;
    sheet.getColumn(7).width = 15;
    sheet.getColumn(8).width = 40;

    // Apply number formats
    sheet.getColumn(1).numFmt = 'yyyy-mm-dd hh:mm:ss';
    sheet.getColumn(6).numFmt = '₦#,##0.00';

    this.applyBrandedFormatting(sheet, branding);
  }

  /**
   * Formats sheet headers with NEM branding
   * 
   * Requirements: 3.4
   */
  private formatSheetHeader(row: ExcelJS.Row, branding: NEMBranding): void {
    row.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    row.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF800020' }, // Burgundy
    };
    row.height = 20;
    row.alignment = { vertical: 'middle', horizontal: 'left' };
  }

  /**
   * Applies NEM color scheme to sheet
   * 
   * Requirements: 3.11
   */
  private applyBrandedFormatting(sheet: ExcelJS.Worksheet, branding: NEMBranding): void {
    // Apply alternating row colors (white and light gold)
    sheet.eachRow((row, rowNumber) => {
      if (rowNumber > 1) { // Skip header row
        if (rowNumber % 2 === 0) {
          row.fill = {
            type: 'pattern',
            pattern: 'solid',
            fgColor: { argb: 'FFFFF8DC' }, // Light Gold
          };
        }
      }
    });

    // Add borders to all cells
    sheet.eachRow((row) => {
      row.eachCell((cell) => {
        cell.border = {
          top: { style: 'thin', color: { argb: 'FFD3D3D3' } },
          left: { style: 'thin', color: { argb: 'FFD3D3D3' } },
          bottom: { style: 'thin', color: { argb: 'FFD3D3D3' } },
          right: { style: 'thin', color: { argb: 'FFD3D3D3' } },
        };
      });
    });
  }
}

// Export singleton instance
export const excelGenerator = new ExcelGenerator();
