import { useState } from 'react';

const initialFormData = {
  companyName: '',
  registeredCompanyAddress: '',
  contactTelephoneNumber: '',
  emailAddress: '',
  website: '',
  contactPerson: '',
  taxIdentificationNumber: '',
  VATRegistrationNumber:'',
  dateOfIncorporationRegistration:'',
  incorporationState:'',
  companyType:[],
  dob:'',
  firstName: '',
  lastName:'',
  residentialAddress:'',
  position:'',
  placeOfBirth:'',
  occupation:'',
  taxIDNumber:'',
  sourceOfIncome:[],
  nationality:'',
  phoneNumber:'',
  email:'',
  idType:[],
  idNumber:'',
  issuedDate:'',
  expiryDate:'',                                                                                                                                                                                                                                         
  issuingBody:'',
  dob2:'',
  firstName2: '',
  lastName2:'',
  residentialAddress2:'', 
  position2:'',
  placeOfBirth2:'',
  occupation2:'',
  taxIDNumber2:'',
  sourceOfIncome2:[],
  nationality2:'',
  phoneNumber2:'',
  email2:'',
  idType2:[],
  idNumber2:'',
  issuedDate2:'',
  expiryDate2:'',                                                                                                                                                                                                                                                
  issuingBody2:'',
  accountNumber:'',
  bankName:'',
  bankBranch:'',
  accountOpeningDate:'',
  accountNumber2:'',
  bankName2:'',
  bankBranch2:'',
  accountOpeningDate2:'',
  identification:null,
  cac:null,
  tax:null,
  cacForm:null,
  privacy:false,
};

const useFormData = () => {
  const [formData, setFormData] = useState(initialFormData);

  return { formData, setFormData };
};

export default useFormData;
