name: Deploy to Firebase Hosting on merge
'on':
 push:
   branches:
     - master
jobs:
 build_and_deploy:
   runs-on: ubuntu-latest
   env:
     REACT_APP_FIREBASE_KEY: ${{ secrets.REACT_APP_FIREBASE_KEY }}
     REACT_APP_FIREBASE_APPID: ${{ secrets.REACT_APP_FIREBASE_APPID }}
     REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID }}
     REACT_APP_MESSENGER_ID: ${{ secrets.REACT_APP_MESSENGER_ID }}
     REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
     REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
     REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
   steps:
     - uses: actions/checkout@v4
     - run: npm ci && npm run build
     - uses: FirebaseExtended/action-hosting-deploy@v0
       with:
         repoToken: '${{ secrets.GITHUB_TOKEN }}'
         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NEM_KYC }}'
         channelId: live
         projectId: nem-kyc
